#!/usr/bin/env bash
# creates a file containing its PID
# displays strings when receiving a SIGTERM signal
# deletes the file and terminates when receiving a SIGQUIT or SIGTERM signal

echo "$$" >> /var/run/myscript.pid

trap 'echo "I hate the kill command" && rm -rf /var/run/myscript.pid && exit 0' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm -rf /var/run/myscript.pid && exit 0' SIGQUIT

for (( ; ; ))
do
	echo "To infinity and beyond"
done
