#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
hour_counter=0
while [ $hour_counter -lt 13 ]; do
	echo "Hour: $hour_counter"
	min_counter=0
	while [ $min_counter -lt 59 ]; do
		(( min_counter+=1 ))
		echo "$min_counter"
	done
	(( hour_counter+=1 ))
done
